version: "3.9"

services:
  user-service:
    container_name: user-service
    build:
      context: ./micro-services/user-service
      dockerfile: ../../docker/microservices/user.dockerfile
    image: mallhive/user-service:latest
  #  env_file:
  #   - ./micro-services/user-service/.env
    ports:
      - "4600:4001"
    depends_on:
      - user-db
    restart: always
    networks:
      - user-net

  user-db:
    image: postgres:15
    container_name: user-db
  #  env_file:
  #   - ./docker-compose/env/user-db.env
    ports:
      - "5430:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - user-net

  order-service:
    container_name: order-service
    build:
      context: ./micro-services/order-service
      dockerfile: ../../docker/microservices/order.dockerfile
    image: mallhive/uorder-service:latest 
  #  env_file:
  #    - ./micro-services/order-service/.env
    ports:
      - "4200:4002"
    depends_on:
      - order-db
    restart: always
    networks:
      - order-net

  order-db:
    image: postgres:15
    container_name: order-db
  #  env_file:
  #    - ./docker-compose/env/order-db.env
    ports:
      - "5440:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - order-net

  payment-service:
    container_name: payment-service
    build:
      context: ./micro-services/payment-service
      dockerfile: ../../docker/microservices/payment.dockerfile
    image: mallhive/order-service:latest 
  #  env_file:
  #    - ./micro-services/payment-service/.env
    ports:
      - "4500:4003"
    restart: always
    networks:
      - payment-net

  product-service:
    container_name: product-service
    build:
      context: ./micro-services/product-service
      dockerfile: ../../docker/microservices/product.dockerfile
    image: mallhive/product-service:latest 
  #  env_file:
  #    - ./micro-services/product-service/.env
    ports:
      - "4100:4004"
    depends_on:
      - product-db
    restart: always
    networks:
      - product-net

  product-db:
    image: postgres:15
    container_name: product-db
  #  env_file:
  #    - ./docker-compose/env/product-db.env
    ports:
      - "5450:5432"
    volumes:
      - product_pgdata:/var/lib/postgresql/data
    networks:
      - product-net

  notification-service:
    container_name: notification-service
    build: 
      context: ./micro-services/notification-service
      dockerfile: ../../docker/microservices/notification.dockerfile
    image: mallhive/notification-service:latest 
  #  env_file:
  #    - ./micro-services/notification-service/.env
    ports:
      - "4400:4005"
    restart: always
    networks:
      - notification-net

  recommendation-service:
    container_name: recommendation-service
    build: 
      context: ./micro-services/recommendation-service
      dockerfile: ../../docker/microservices/recommendation.dockerfile
    image: mallhive/recommendation-service:latest 
  #  env_file:
  #    - ./micro-services/recommendation-service/.env
    ports:
      - "4700:4006"
    restart: always
    networks:
      - recommendation-net

  analytics-service:
    container_name: analytics-service
    build: 
      context: ./micro-services/analytics-service
      dockerfile: ../../docker/microservices/analytics.dockerfile
    image: mallhive/analytics-service:latest 
  #  env_file:
  #    - ./micro-services/analytics-service/.env
    ports:
      - "4800:4007"
    restart: always
    networks:
      - analytics-net

  shoppingcart-service:
    container_name: shoppingcart-service
    build: 
      context: ./micro-services/shoppingcart-service
      dockerfile: ../../docker/microservices/shoppingcart.dockerfile
    image: mallhive/shoppingcart-service:latest 
  #  env_file:
  #    - ./micro-services/shoppingcart-service/.env
    ports:
      - "4300:4008"
    restart: always
    networks:
      - shoppingcart-net

  checkout-microfrontend:
    container_name: checkout-microfrontend
    build: 
      context: ./microfrontends/checkout-microfrontend
      dockerfile: ../../docker/microfrontends/checkout.dockerfile
    image: mallhive/checkout-microfrontend:latest 
    ports:
      - "3400:3000"
    restart: always
    networks:
      - checkout-net

  homepage-microfrontend:
    container_name: homepage-microfrontend
    build: 
      context: ./microfrontends/homepage-microfrontend
      dockerfile: ../../docker/microfrontends/homepage.dockerfile
    image: mallhive/homepage-microfrontend:latest 
    ports:
      - "3100:3000"
    restart: always
    networks:
      - homepage-net

  product-microfrontend:
    container_name: product-microfrontend
    build: 
      context: ./microfrontends/product-microfrontend
      dockerfile: ../../docker/microfrontends/product.dockerfile
    image: mallhive/product-microfrontend:latest 
    ports:
      - "3200:3000"
    restart: always
    networks:
      - product-mf-net

  shoppingcart-microfrontend:
    container_name: shoppingcart-microfrontend
    build: 
      context: ./microfrontends/shoppingcart-microfrontend
      dockerfile: ../../docker/microfrontends/shoppingcart.dockerfile
    image: mallhive/shoppingcart-microfrontend:latest 
    ports:
      - "3300:3000"
    restart: always
    networks:
      - shoppingcart-mf-net

  userprofile-microfrontend:
    container_name: userprofile-microfrontend
    build: 
      context: ./microfrontends/userprofile-microfrontend
      dockerfile: ../../docker/microfrontends/userprofile.dockerfile
    image: mallhive/userprofile-microfrontend:latest 
    ports:
      - "3500:3000"
    restart: always
    networks:
      - userprofile-net

volumes:
  user_pgdata:
  order_pgdata:
  product_pgdata:

networks:
  user-net:
  order-net:
  payment-net:
  product-net:
  notification-net:
  recommendation-net:
  analytics-net:
  shoppingcart-net:
  checkout-net:
  homepage-net:
  product-mf-net:
  shoppingcart-mf-net:
  userprofile-net:
